import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {freshProgress,cleanProgress,mergeProgress,hasLearning} from '../src/progress.js';
import {emptyConversation,finishStage,reviewConversation,transcriptMatch} from '../src/conversation-memory.js';
const stories=JSON.parse(readFileSync(new URL('../src/conversations.json',import.meta.url)));
test('48 bilingual scenes keep a coherent two-person script and cover every unit in each level',()=>{
 for(const [level,chapters]of Object.entries(stories)){assert.equal(chapters.length,6);assert.deepEqual(chapters.flatMap(c=>c.units).sort((a,b)=>a-b),Array.from({length:24},(_,i)=>i+1));
 for(const c of chapters){assert.equal(c.people.length,2);assert.equal(c.episodes.length,2);for(const e of c.episodes){assert.equal(e.lines.length,8);assert.equal(e.chunks.length,3);assert.equal(e.branches.length,2);assert(e.task.length>30&&e.context.length>30);e.lines.forEach((l,i)=>{assert.equal(l.speaker,i%2);assert(l.en&&l.es);});for(const phrase of e.chunks)assert(phrase.use.length>30&&phrase.example&&phrase.translation);for(const b of e.branches)assert(b.en&&b.es&&b.reply&&b.translation&&b.why.length>30);}}
 }
});
test('old progress preserves lessons and conversation imports reject invalid keys, stages and oversized text',()=>{const p=freshProgress();p.completed['1_0']={score:100,date:'2026-10-11'};p.conversations={c1e0:{done:[5,5,-1,1,9],attempts:3,correct:90,draft:'x'.repeat(5000)},c7e0:{done:[1]},c1e2:{done:[2]}};const v=cleanProgress(p);assert.deepEqual(Object.keys(v.conversations),['c1e0']);assert.deepEqual(v.conversations.c1e0.done,[1,5]);assert.equal(v.conversations.c1e0.correct,3);assert.equal(v.conversations.c1e0.draft.length,1800);assert.deepEqual(v.completed,p.completed);assert(hasLearning(v));});
test('the first recall is scheduled only after all six distinct stages and early review cannot skip an interval',()=>{let p=emptyConversation();for(let i=0;i<5;i++){p=finishStage(p,i,100);assert.equal(p.review[3],0);}p=finishStage(p,5,100);assert.equal(p.review[3],86400100);assert.equal(finishStage(p,5,500).review[3],p.review[3]);p=reviewConversation(p,true,p.review[3]);assert.equal(p.review[2],1);const due=p.review[3];p=reviewConversation(p,true,due-500);assert.equal(p.review[2],1);assert.equal(p.review[3],due);p=reviewConversation(p,false,due);assert.equal(p.review[2],0);assert.equal(p.review[3],due+900000);});
test('parallel devices combine distinct conversation steps, keep the latest draft, and add only new attempts',()=>{const base=freshProgress();base.conversations.c1e0={...emptyConversation(),done:[0],attempts:1,correct:1,updated:10};const l=structuredClone(base),r=structuredClone(base);l.conversations.c1e0={...l.conversations.c1e0,done:[0,1],draft:'Local draft',attempts:3,correct:2,updated:20};r.conversations.c1e0={...r.conversations.c1e0,done:[0,2],draft:'Newer remote draft',attempts:2,correct:2,updated:30};r.conversations.c2e0={...emptyConversation(),done:[0],updated:40};const out=mergeProgress(base,l,r);assert.deepEqual(out.conversations.c1e0.done,[0,1,2]);assert.equal(out.conversations.c1e0.draft,'Newer remote draft');assert.equal(out.conversations.c1e0.attempts,4);assert.equal(out.conversations.c1e0.correct,3);assert(out.conversations.c2e0);assert.deepEqual(mergeProgress(out,out,out),out);});
test('transcript matching counts only word overlap, handles empty and very different replies',()=>{assert.equal(transcriptMatch('Hello, Mia!','hello mia'),100);assert.equal(transcriptMatch('', 'hello'),0);assert.equal(transcriptMatch('different words','hello Mia'),0);assert.equal(transcriptMatch('hello Mia','hello dear Mia'),67);});
