import stories from './conversations.json';
import {sceneArt,avatar} from './conversation-art.js';
import {episodeKey,emptyConversation,finishStage,reviewConversation,sceneComplete,transcriptMatch} from './conversation-memory.js';
import {addLearningEvent} from './practice-memory.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stages=['Comprende','Descubre','Responde','Habla','Decide','Úsalo'];
let ctx=null,utterance=null,resolveSpeech=null,audioToken=0,recorder=null,stream=null,recognition=null,audioURL=null,recordingPending=false;
const get=(id)=>document.getElementById(id);
const link=(c,e,s=0)=>`#conversation/${c}/${e}/${s}`;
const button=(action,label,cls='soft',extra='')=>`<button class="btn ${cls}" data-cv="${action}" ${extra}>${label}</button>`;
const pct=v=>Math.round((v?.done?.length||0)/6*100);
const date=t=>new Date(t).toLocaleDateString('es',{day:'numeric',month:'short'});
export function conversationForUnit(level,id){return stories[level]?.find(c=>c.units.includes(Number(id)));}
export function conversationLink(level,unit){const c=conversationForUnit(level,unit);return c?`<a class="cv-unit-link" href="${link(c.id,0)}"><span>PRIMERO, UNA SITUACIÓN REAL</span><b>${esc(c.title)} →</b><small>Escucha, comprende y practica tu papel en la conversación.</small></a>`:'';}
export function renderConversationHome(store,course){
 const level=store.courseId,list=stories[level],p=store.getState(),all=list.flatMap(c=>c.episodes.map((e,i)=>({c,e,i,v:p.conversations[episodeKey(c.id,i)]}))),complete=all.filter(x=>sceneComplete(x.v)),next=all.find(x=>!sceneComplete(x.v))||all[0],stage=stages.findIndex((_,i)=>!next.v?.done?.includes(i)),due=all.filter(x=>sceneComplete(x.v)&&x.v.review[3]<=Date.now()),started=all.filter(x=>x.v?.done?.length).length;
 const levelDescriptions={a1:'Conoce gente, pide algo en un café y organiza tus primeros planes.',a2:'Resuelve pequeños imprevistos y cuenta lo que te ha pasado.',b1:'Explica, aclara y mantén conversaciones con más independencia.',b2:'Negocia, argumenta y responde con matices en situaciones complejas.'};
 const history=(p.studyLog||[]).filter(x=>x.kind==='conversation').slice(0,5);
 return `<div class="cv-journey"><section class="cv-hero"><div class="cv-hero-copy"><span class="cv-tag">TU INGLÉS, EN LA VIDA REAL · ${level.toUpperCase()}</span><h2>Habla inglés.<br><em>Una historia a la vez.</em></h2><p>${levelDescriptions[level]} Primero entiendes la historia. Después participas y la llevas a tu vida.</p><a class="btn primary" href="${link(next.c.id,next.i,Math.max(0,stage))}">${started?'Continuar mi historia':'Empezar mi primera historia'} <span aria-hidden="true">↗</span></a><p class="cv-small">Sin límite de intentos. Puedes volver a escuchar y equivocarte.</p></div><div class="cv-hero-picture">${sceneArt(next.c.theme,next.c.people)}<div class="cv-picture-label">${avatar(next.c.people[0])}<span><b>Tu siguiente conversación</b><small>${esc(next.e.title)}</small></span></div></div></section>
 <div class="cv-stats"><div><b>${complete.length}<small> / 12</small></b><span>escenas recorridas en ${level.toUpperCase()}</span></div><div><b>${all.reduce((n,x)=>n+(x.v?.done?.length||0),0)}<small> / 72</small></b><span>pasos practicados</span></div><div><b>${due.length}</b><span>conversaciones para recordar</span></div><a href="#skills/history">Ver mi historial ↗</a></div>
 <section class="cv-how" aria-label="Cómo aprender con estas historias"><span><b>01</b> Entiende con apoyo</span><span><b>02</b> Responde en contexto</span><span><b>03</b> Habla con tu voz</span><span><b>04</b> Recuerda otro día</span></section>
 ${due.length?`<section class="cv-review-banner"><div><span class="cv-tag">UN POCO DE MEMORIA, ANTES DE SEGUIR</span><h3>${due.length===1?'Una conversación vuelve hoy':due.length+' conversaciones vuelven hoy'}</h3><p>Intenta recordar las expresiones antes de abrir el modelo.</p></div><a class="btn primary" href="${link(due[0].c.id,due[0].i,6)}">Repasar ${esc(due[0].e.title)} →</a></section>`:''}
 <div class="cv-section-title"><div><span class="cv-tag">6 HISTORIAS · 12 ESCENAS · NIVEL ${level.toUpperCase()}</span><h2>Un lugar. Un motivo para hablar.</h2></div><span class="cv-small">Elige una historia o sigue el orden.</span></div>
 <div class="cv-chapters">${list.map(c=>`<article class="cv-chapter"><a class="cv-cover" href="${link(c.id,0)}" aria-label="Abrir ${esc(c.title)}">${sceneArt(c.theme,c.people)}<span class="cv-chapter-no">${String(c.id).padStart(2,'0')}</span></a><div class="cv-chapter-copy"><span class="cv-small">${esc(c.people.join(' + '))} · 2 escenas conectadas</span><h3>${esc(c.title)}</h3><div class="cv-episode-list">${c.episodes.map((e,i)=>{const v=p.conversations[episodeKey(c.id,i)],n=stages.findIndex((_,s)=>!v?.done?.includes(s));return `<a href="${link(c.id,i,Math.max(0,n))}"><span class="cv-step-dot ${sceneComplete(v)?'is-done':''}">${sceneComplete(v)?'✓':i+1}</span><span><b>${esc(e.title)}</b><small>${v?.done?.length?`${v.done.length} de 6 pasos practicados`:'Escucha · responde · habla'}</small><span class="cv-mini-progress"><i style="width:${pct(v)}%"></i></span></span><span aria-hidden="true">→</span></a>`;}).join('')}</div><details><summary>Gramática y talleres de apoyo</summary><p class="cv-small">Profundiza en estas unidades cuando necesites más explicación.</p>${c.units.map(n=>`<a href="#unit/${n}">${n}. ${esc(course.units[n-1].title)}</a>`).join('')}</details></div></article>`).join('')}</div>
 <div class="cv-bottom-grid"><section class="panel"><span class="cv-tag">DE ENTENDER A PARTICIPAR</span><h3>De la historia a tu propia vida</h3><p>Usa expresiones completas, cambia un dato, grábate y vuelve a intentarlo sin mirar. Recorrer las pantallas marca práctica realizada; la soltura llega al poder usar lo aprendido en otras situaciones.</p><a href="#study" class="text-link">Explorar los 24 talleres del nivel →</a></section><section class="panel"><span class="cv-tag">TUS ÚLTIMOS PASOS</span><h3>Lo que sí has practicado</h3>${history.length?history.map(x=>`<p class="cv-history-row"><span>Conversación · unidad ${x.unit}</span><small>${date(x.t)}</small></p>`).join(''):'<p>Tu historial aparecerá cuando practiques. No necesitas crear una cuenta para empezar.</p>'}<a href="#account" class="text-link">${store.user?'Mi cuenta y sincronización':'Guardar con Google o descargar mi progreso'} →</a></section></div><section class="cv-tools"><a href="#lab"><b>44 sonidos y boca animada</b><span>Observa, escucha y prueba →</span></a><a href="#skills/reading"><b>Lectura y comprensión</b><span>Más textos según tu nivel →</span></a><a href="#route"><b>Gramática y unidades</b><span>Consulta todas las explicaciones →</span></a></section><p class="cv-small">Conversaciones guiadas escritas para practicar. Las voces dependen de las voces inglesas disponibles en tu navegador. Los textos y traducciones están siempre disponibles.</p></div>`;
}
export function renderConversation(store,course,id,index=0,stage=0){
 const story=stories[store.courseId]?.find(x=>x.id===Number(id));index=Number(index);stage=Number(stage);
 if(!story||![0,1].includes(index)||!Number.isInteger(stage)||stage<0||stage>6)return `<section class="panel"><h2>Esa escena no existe</h2><a href="#journey" class="btn primary">Volver a las historias</a></section>`;
 const episode=story.episodes[index],key=episodeKey(story.id,index),record=store.getState().conversations[key]||emptyConversation();
 ctx={store,course,story,episode,index,stage,key,visible:record.done.includes(0)?8:2,mode:'both',rate:.85,seen:new Set(),turn:0,voiceTurn:0,selected:null,feedback:'',choice:record.choice,model:false,practised:new Set(),heard:false,recorded:false,typed:'',recallOpen:false,recallValues:['','','']};
 const html=`<div class="cv-course" id="conversation"><div class="cv-course-top"><a href="#journey" class="back-link">← Todas las historias</a><span>${store.courseId.toUpperCase()} · Historia ${story.id} · Escena ${index+1}/2</span></div><section class="cv-scene-head"><div><span class="cv-tag">${esc(story.title)}</span><h2>${esc(episode.title)}</h2><p>${esc(episode.context)}</p><div class="cv-cast">${story.people.map((n,i)=>`<span>${avatar(n,i)}<b>${esc(n)}${i===1?' · tú':''}</b></span>`).join('')}</div></div><div class="cv-scene-visual">${sceneArt(story.theme,story.people)}</div></section><nav class="cv-stages" aria-label="Pasos de esta escena">${stages.map((n,i)=>`<a href="${link(story.id,index,i)}" ${stage===i?'aria-current="step"':''} class="${record.done.includes(i)?'is-done':''}"><span>${record.done.includes(i)?'✓':i+1}</span>${n}</a>`).join('')}</nav><div id="cv-status" class="cv-status" role="status" aria-live="polite"></div><div id="cv-body">${stageBody()}</div><aside class="cv-support"><details><summary>Necesito más explicación o vocabulario</summary><p>Usa estos apoyos y después vuelve a la escena. En el texto, pasa el mouse sobre una palabra o tócala para traducirla. El morado identifica vocabulario de aprendizaje todavía sin marcar como recordado.</p>${story.units.map(n=>`<a href="#unit/${n}">${n}. ${esc(course.units[n-1].title)}</a>`).join('')}<a href="#lab">Laboratorio de los 44 sonidos →</a></details></aside></div>`;
 return html;
}
function rec(){return ctx.store.getState().conversations[ctx.key]||emptyConversation();}
function save(change){if(!ctx)return;const p=ctx.store.getState();p.conversations[ctx.key]={...rec(),...change,updated:Date.now()};ctx.store.save(p);}
function event(){const p=ctx.store.getState(),day=new Date().toLocaleDateString('en-CA');addLearningEvent(p,'conversation',ctx.story.units[ctx.index*2],0,0);p.activity[day]=Math.min(10000,(p.activity[day]||0)+1);ctx.store.save(p);}
function complete(){if(!ctx)return;const v=rec();save(finishStage(v,ctx.stage));if(!v.done.includes(ctx.stage))event();location.hash=ctx.stage===5?'journey':link(ctx.story.id,ctx.index,ctx.stage+1);}
function paint(){if(get('cv-body')&&ctx){get('cv-body').innerHTML=stageBody();restoreRecordingUI();}}
function restoreRecordingUI(){if(get('cv-recording')&&audioURL){get('cv-recording').innerHTML='<p class="cv-small">Tu grabación. Escúchala y compárala con el modelo.</p><audio controls id="cv-playback" aria-label="Escuchar mi grabación"></audio>';get('cv-playback').src=audioURL;}if(get('cv-record')&&recorder?.state==='recording')get('cv-record').textContent='■ Terminar grabación';}
function status(message){if(get('cv-status'))get('cv-status').textContent=message;}
function controls(){return `<div class="cv-audio-tools"><label>Velocidad <select id="cv-rate"><option value=".65" ${ctx.rate===.65?'selected':''}>Lenta</option><option value=".85" ${ctx.rate===.85?'selected':''}>Tranquila</option><option value="1" ${ctx.rate===1?'selected':''}>Natural</option></select></label><label>Apoyo <select id="cv-mode"><option value="both" ${ctx.mode==='both'?'selected':''}>Inglés + español</option><option value="en" ${ctx.mode==='en'?'selected':''}>Solo inglés</option><option value="audio" ${ctx.mode==='audio'?'selected':''}>Solo escuchar</option></select></label>${button('stop-audio','■ Detener','ghost')}</div>`;}
function bubble(line,i,{hidden=false,translate=true}={}){return `<div class="cv-bubble-row ${line.speaker?'cv-you':''}" data-line="${i}">${avatar(ctx.story.people[line.speaker],line.speaker)}<div class="cv-bubble"><span class="cv-speaker">${esc(ctx.story.people[line.speaker])}${line.speaker?' · tu papel':''}</span>${hidden?'<p class="cv-hidden-caption">Intenta entender sin leer.</p>':`<p class="cv-english" lang="en">${esc(line.en)}</p>${translate?`<p class="cv-translation">${esc(line.es)}</p>`:''}`}<button class="cv-listen" data-cv="line" data-line-id="${i}" aria-label="Escuchar intervención de ${esc(ctx.story.people[line.speaker])}">▶ Escuchar</button></div></div>`;}
function completeButton(enabled,label='Continuar al siguiente paso'){return `<div class="cv-step-footer">${button('complete',label,'primary',enabled?'':'disabled')}<span class="cv-small">Puedes repetir este paso cuando quieras.</span></div>`;}
function stageBody(){if(!ctx)return'';const e=ctx.episode,v=rec();switch(ctx.stage){
 case 0:return `<section class="cv-panel"><div class="cv-section-title"><div><span class="cv-tag">1 · PRIMERO ENTIENDE LA SITUACIÓN</span><h3>Escucha cómo empieza todo</h3></div>${button('play-all','▶ Escuchar conversación','primary')}</div><p>Lee con la traducción al principio. Cuando entiendas, elige «Solo inglés» o «Solo escuchar» y vuelve a escuchar.</p>${controls()}<div class="cv-dialogue">${e.lines.slice(0,ctx.visible).map((l,i)=>bubble(l,i,{hidden:ctx.mode==='audio',translate:ctx.mode==='both'})).join('')}</div><div class="button-row">${ctx.visible<8?button('next-line','Seguir la conversación ↓','soft')+button('show-all','Ver la conversación completa','ghost'):''}</div><p class="cv-small">${ctx.visible} de 8 intervenciones · No necesitas memorizarlo todo. Fíjate en qué quiere cada persona.</p>${completeButton(ctx.visible===8,'Ya comprendo la situación →')}</section>`;
 case 1:return `<section class="cv-panel"><span class="cv-tag">2 · EXPRESIONES QUE TE LLEVAS CONTIGO</span><h3>Aprende lo que puedes volver a usar</h3><p>No necesitas traducir palabra por palabra. Descubre para qué sirve cada expresión, escucha otro ejemplo y piensa dónde la usarías.</p><div class="cv-phrases">${e.chunks.map((ch,i)=>`<article class="cv-phrase"><span class="cv-small">EXPRESIÓN ${i+1}</span><h4 lang="en">${esc(ch.en)}</h4>${ctx.seen.has(i)?`<p class="cv-translation">${esc(ch.es)}</p><p>${esc(ch.use)}</p><div class="cv-example"><p lang="en">${esc(ch.example)}</p><small>${esc(ch.translation)}</small>${button('phrase-audio','▶ Escuchar ejemplo','ghost',`data-idx="${i}"`)}</div><p class="cv-small">Di una frase parecida cambiando una persona, un lugar o una necesidad.</p>`:button('phrase', 'Descubrir significado y uso','soft',`data-idx="${i}"`)}</article>`).join('')}</div>${completeButton(ctx.seen.size===3,'Ya exploré las tres expresiones →')}</section>`;
 case 2:{const t=ctx.turn;if(t>=4)return `<section class="cv-panel cv-celebrate"><span class="cv-round-check">✓</span><h3>Has mantenido el hilo</h3><p>Respondiste los cuatro turnos de ${esc(ctx.story.people[1])}. Ahora vas a decirlos con tu propia voz.</p><p class="cv-small">Este ejercicio comprueba que reconozcas el turno del guion que encaja aquí. En una conversación real puede haber muchas respuestas válidas.</p>${completeButton(true,'Pasar a hablar →')}</section>`;const at=t*2,correct=e.lines[at+1],options=[1,3,5,7].filter(n=>n!==at+1).slice(0,2).concat(at+1).sort((a,b)=>((a+ctx.story.id+t)%9)-((b+ctx.story.id+t)%9));return `<section class="cv-panel"><span class="cv-tag">3 · TU PAPEL EN LA MISMA HISTORIA · ${t+1}/4</span><h3>¿Cómo continúa este momento?</h3><p>Escucha lo que acaba de decir ${esc(ctx.story.people[0])}. Elige el turno del diálogo que responde a esa intención.</p>${bubble(e.lines[at],at)}<p class="cv-task-cue"><b>Tu intención:</b> ${esc(correct.es)}</p><div class="cv-answer-options" data-no-translate>${options.map(n=>`<button data-cv="answer" data-idx="${n}" class="${ctx.selected===n?'is-selected':''}" ${ctx.feedback==='correct'?'disabled':''}><span aria-hidden="true">↳</span><span lang="en">${esc(e.lines[n].en)}</span></button>`).join('')}</div>${ctx.feedback?`<div class="cv-feedback ${ctx.feedback==='correct'?'is-correct':''}" role="status">${ctx.feedback==='correct'?`<b>La conversación continúa.</b><p>${esc(correct.es)}</p><p>Tu respuesta se conecta con lo que ${esc(ctx.story.people[0])} acaba de decir.</p>${button('next-turn',t===3?'Terminar diálogo →':'Escuchar el siguiente turno →','primary')}`:`<b>Vuelve a mirar la situación.</b><p>Esa frase aparece en otro momento de esta historia. Aquí necesitas responder a: «${esc(e.lines[at].es)}».</p><p>Tu intención es: ${esc(correct.es)}</p>`}</div>`:''}<details class="cv-model"><summary>Revisar el turno del guion</summary><p lang="en">${esc(correct.en)}</p><p>${esc(correct.es)}</p></details></section>`;}
 case 3:{const t=ctx.voiceTurn;if(t>=4)return `<section class="cv-panel cv-celebrate"><span class="cv-round-check">✓</span><h3>La conversación ya tiene tu voz</h3><p>Practicaste los cuatro turnos. En el siguiente paso podrás elegir cómo termina esta escena.</p>${completeButton(true,'Elegir cómo continúa →')}</section>`;const at=t*2,model=e.lines[at+1];return `<section class="cv-panel"><span class="cv-tag">4 · ESCUCHA Y RESPONDE · ${t+1}/4</span><h3>Ahora ${esc(ctx.story.people[1])} eres tú</h3><p>Escucha a ${esc(ctx.story.people[0])}, haz una pausa y responde. Puedes usar tus palabras o repetir el modelo para ganar soltura.</p>${bubble(e.lines[at],at,{hidden:ctx.mode==='audio',translate:ctx.mode==='both'})}${controls()}<div class="cv-speaking-card">${avatar(ctx.story.people[1],1)}<div><h4>Tu intención</h4><p>${esc(model.es)}</p><div class="button-row">${button('toggle-model',ctx.model?'Ocultar el modelo':'Necesito ver el modelo','ghost')}${button('model-audio','▶ Escuchar el modelo','ghost')}</div>${ctx.model?`<p lang="en" class="cv-model-text">${esc(model.en)}</p>`:''}</div></div><div class="cv-voice-tools"><h4>Escúchate y vuelve a intentarlo</h4><div class="button-row">${button('record','● Grabar mi voz','soft','id="cv-record"')}${button('recognise','Usar dictado de voz','ghost','id="cv-recognise"')}</div><div id="cv-recording"></div><label for="cv-own-words">Tu respuesta, escrita o dictada (opcional)</label><textarea id="cv-own-words" lang="en" rows="3" maxlength="1800" placeholder="Try your reply here…">${esc(ctx.typed)}</textarea>${button('compare','Comparar palabras con el guion','ghost')}<div id="cv-comparison" role="status"></div><p class="cv-small">La grabación se escucha aquí y se descarta al salir de esta escena. El dictado depende del navegador y puede usar su servicio de voz. La coincidencia de palabras no mide tu acento ni la calidad de una respuesta libre.</p></div><div class="cv-step-footer">${button('voice-next','Ya practiqué: siguiente turno →','primary')}<span class="cv-small">También puedes responder en voz alta sin activar el micrófono.</span></div></section>`;}
 case 4:return `<section class="cv-panel"><span class="cv-tag">5 · DOS CAMINOS POSIBLES</span><h3>Decide qué quieres conseguir</h3><p>Ensaya dos variantes de este momento. Las dos opciones son válidas: cada una provoca una respuesta distinta.</p>${bubble(e.lines[7],7)}<div class="cv-branches">${e.branches.map((b,i)=>`<button data-cv="branch" data-idx="${i}" aria-pressed="${ctx.choice===i}" class="${ctx.choice===i?'is-selected':''}"><span class="cv-tag">OPCIÓN ${i+1}</span><b lang="en">${esc(b.en)}</b><span>${esc(b.es)}</span></button>`).join('')}</div>${ctx.choice>=0?`<div class="cv-branch-result"><div class="cv-bubble-row">${avatar(ctx.story.people[0])}<div class="cv-bubble"><span class="cv-speaker">${esc(ctx.story.people[0])} responde</span><p lang="en">${esc(e.branches[ctx.choice].reply)}</p><p class="cv-translation">${esc(e.branches[ctx.choice].translation)}</p>${button('branch-audio','▶ Escuchar respuesta','ghost')}</div></div><div class="cv-notice"><b>Qué consigues con esa frase</b><p>${esc(e.branches[ctx.choice].why)}</p></div><p class="cv-small">Prueba también el otro camino y compara el efecto. El siguiente episodio retoma el guion principal; estas variantes sirven para ensayar otras posibilidades.</p></div>`:''}${completeButton(ctx.choice>=0,'Llevarlo a mi vida →')}</section>`;
 case 5:{const done=sceneComplete(v);return `<section class="cv-panel"><span class="cv-tag">6 · CAMBIA LA SITUACIÓN</span><h3>La siguiente conversación es tuya</h3><div class="cv-notice"><b>Tu reto</b><p>${esc(e.task)}</p></div><p>Imagina dos personas. Escribe un pequeño intercambio o una respuesta que usarías de verdad. Cambia al menos un detalle de la historia.</p><label for="cv-draft">Mi conversación o respuesta en inglés</label><textarea id="cv-draft" rows="6" maxlength="1800" lang="en" placeholder="Write your own version…">${esc(v.draft)}</textarea><span id="cv-save-note" class="cv-small">Borrador guardado automáticamente en este navegador${ctx.store.user?' y en tu cuenta al sincronizar':''}.</span><details class="cv-model"><summary>Necesito apoyo para empezar</summary><p>Reutiliza estas expresiones, pero cambia la información para responder al reto:</p>${e.chunks.map(c=>`<p><b lang="en">${esc(c.en)}</b><br>${esc(c.use)}</p>`).join('')}<a href="${link(ctx.story.id,ctx.index,0)}">Volver a leer la escena →</a></details><fieldset class="cv-self-check"><legend>Revisa lo que has conseguido</legend><label><input type="checkbox" data-cv-check> Mi respuesta tiene sentido en la situación.</label><label><input type="checkbox" data-cv-check> Usé una expresión de la escena y cambié información.</label><label><input type="checkbox" data-cv-check> La dije en voz alta y sé qué quiero comunicar.</label></fieldset><label for="cv-reflection">¿Qué te costó y qué quieres volver a intentar? (opcional)</label><textarea id="cv-reflection" maxlength="1800" rows="2">${esc(v.reflection)}</textarea><p class="cv-small">Esta creación es una autoevaluación. La página no corrige automáticamente la gramática de un texto libre. Recorrer la escena no equivale a demostrar dominio del nivel.</p><div class="cv-step-footer">${button('finish',done?'Guardar mi nueva práctica →':'Guardar y terminar esta escena →','primary','id="cv-finish" disabled')}<span class="cv-small">Escribe tu versión y completa la revisión. Cuando termines los seis pasos, habrá un repaso para otro día.</span></div></section>`;}
 case 6:return `<section class="cv-panel"><span class="cv-tag">VUELVE A RECORDAR · REPASO ESPACIADO</span><h3>¿Qué dirías sin mirar?</h3><p>Recuerda la historia «${esc(e.title)}». Intenta recuperar estas expresiones. Después mira los modelos y decide si necesitas volver a practicarlas.</p><div class="cv-phrases">${e.chunks.map((ch,i)=>`<article class="cv-phrase"><label for="cv-recall-${i}">${esc(ch.es)}</label><input id="cv-recall-${i}" data-cv-recall="${i}" lang="en" value="${esc(ctx.recallValues[i])}" placeholder="Try to remember…" maxlength="300">${ctx.recallOpen?`<p lang="en"><b>${esc(ch.en)}</b></p><p>${esc(ch.use)}</p><p lang="en">${esc(ch.example)}</p>${button('phrase-audio','▶ Escuchar ejemplo','ghost',`data-idx="${i}"`)}`:''}</article>`).join('')}</div>${ctx.recallOpen?`<p>Esta valoración es tuya: una formulación distinta también puede expresar la misma idea. Compara el uso y el significado, no solo la escritura.</p><div class="button-row">${button('recall-good','Las pude recuperar','primary')}${button('recall-hard','Necesito practicarlas otra vez','soft')}</div>`:button('recall-show','Ya lo intenté: ver los modelos','primary')}<p class="cv-small">Si necesitas más apoyo, volverán en unos 15 minutos. Cuando las recuerdes en repasos separados, el intervalo aumentará hasta 30 días. Repetir antes de la fecha no salta intervalos.</p></section>`;
 }}
function highlight(line,speaker){document.querySelectorAll('#conversation .cv-bubble-row').forEach(x=>x.classList.toggle('is-speaking',Number(x.dataset.line)===line));document.querySelectorAll('#conversation .cv-person').forEach(x=>x.classList.toggle('is-speaking',x.classList.contains('cv-person-'+speaker)));}
function stopSpeech(){audioToken++;if('speechSynthesis'in window)window.speechSynthesis.cancel();if(resolveSpeech)resolveSpeech(false);resolveSpeech=null;utterance=null;highlight(-99,-99);}
async function speak(text,speaker=0,line=-1){
 stopSpeech();if(!ctx)return false;if(!('speechSynthesis'in window)){status('No hay lectura en voz alta en este navegador. Puedes seguir el texto y practicar sin audio.');return false;}const current=ctx,token=audioToken;
 if(recorder?.state==='recording')stopRecording();if(recognition){recognition.abort();recognition=null;}
 return await new Promise(resolve=>{resolveSpeech=resolve;let ended=false;const finish=ok=>{if(ended)return;ended=true;if(token===audioToken){resolveSpeech=null;utterance=null;highlight(-99,-99);}resolve(ok);};
 try{utterance=new SpeechSynthesisUtterance(text);utterance.lang=ctx.store.getState().accent;utterance.rate=ctx.rate;const voices=window.speechSynthesis.getVoices().filter(v=>v.lang.replace('_','-').startsWith(utterance.lang)),english=voices.length?voices:window.speechSynthesis.getVoices().filter(v=>v.lang.startsWith('en'));utterance.voice=english[speaker%Math.max(1,english.length)]||null;utterance.pitch=speaker?1.08:1;utterance.onstart=()=>{if(ctx===current&&token===audioToken)highlight(line,speaker);};utterance.onend=()=>finish(true);utterance.onerror=ev=>{if(!['interrupted','canceled'].includes(ev.error))status('No se pudo reproducir esta voz. Revisa las voces inglesas de tu navegador o usa el texto.');finish(false);};window.speechSynthesis.speak(utterance);}catch{status('La voz no está disponible. Puedes leer el diálogo.');finish(false);}});
}
async function playAll(){const current=ctx;stopSpeech();ctx.visible=8;paint();status('Escuchando la conversación. Puedes detenerla cuando quieras.');for(let i=0;i<8;i++){if(ctx!==current)return;const l=ctx.episode.lines[i];const ok=await speak(l.en,l.speaker,i);if(!ok||ctx!==current)return;}save({plays:rec().plays+1});status('Conversación escuchada. Prueba otra vez sin traducción cuando la entiendas.');}
function revokeAudio(){if(audioURL){URL.revokeObjectURL(audioURL);audioURL=null;}}
function stopRecording(){recordingPending=false;if(recorder?.state==='recording')recorder.stop();stream?.getTracks().forEach(t=>t.stop());stream=null;const b=get('cv-record');if(b){b.textContent='● Grabar mi voz';b.disabled=false;}}
async function record(){
 if(recorder?.state==='recording'){stopRecording();return;}if(recordingPending)return;
 if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status('La grabación no está disponible aquí. Abre la página con HTTPS en un navegador compatible o practica en voz alta.');return;}
 stopSpeech();recognition?.abort();recognition=null;const current=ctx,turn=ctx.voiceTurn;recordingPending=true;get('cv-record').disabled=true;status('Permite el micrófono para grabar. El audio queda solo en esta página.');
 try{const acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(ctx!==current||ctx.voiceTurn!==turn||!recordingPending){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;recordingPending=false;const parts=[];recorder=new MediaRecorder(stream);const recording=recorder;recording.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};recording.onstop=()=>{if(ctx!==current||ctx.voiceTurn!==turn)return;revokeAudio();audioURL=URL.createObjectURL(new Blob(parts,{type:recording.mimeType||'audio/webm'}));restoreRecordingUI();status('Grabación lista para escuchar. Puedes grabar otra toma.');};recording.onerror=()=>{stopRecording();status('No se pudo grabar. Puedes responder sin micrófono.');};recording.start();get('cv-record').disabled=false;get('cv-record').textContent='■ Terminar grabación';status('Grabando… pulsa «Terminar grabación» cuando acabes.');}catch{if(ctx!==current)return;recordingPending=false;get('cv-record')&&(get('cv-record').disabled=false);status('No se pudo acceder al micrófono. Revisa el permiso o practica en voz alta sin grabar.');}
}
function recognise(){if(recognition){recognition.abort();recognition=null;status('Dictado detenido.');return;}const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API){status('Este navegador no ofrece dictado. Puedes grabarte o escribir tu respuesta.');return;}stopSpeech();stopRecording();const current=ctx;recognition=new API();recognition.lang=ctx.store.getState().accent;recognition.interimResults=false;recognition.continuous=false;recognition.onresult=e=>{if(ctx!==current)return;ctx.typed=e.results[0][0].transcript;if(get('cv-own-words'))get('cv-own-words').value=ctx.typed;status('Esto es lo que entendió el servicio de voz. Puedes corregir la transcripción.');};recognition.onerror=e=>{if(ctx===current)status(e.error==='not-allowed'?'El micrófono no tiene permiso. Puedes escribir tu respuesta.':'No se pudo transcribir. Intenta de nuevo o escribe tu respuesta.');};recognition.onend=()=>{recognition=null;if(get('cv-recognise'))get('cv-recognise').textContent='Usar dictado de voz';};try{recognition.start();get('cv-recognise').textContent='Detener dictado';status('Escuchando tu respuesta…');}catch{recognition=null;status('No se pudo iniciar el dictado. Puedes escribir tu respuesta.');}}
export function stopConversations(){ctx=null;stopSpeech();recognition?.abort();recognition=null;stopRecording();recorder=null;revokeAudio();}
function finishReady(){const el=get('cv-finish');if(el)el.disabled=!(get('cv-draft')?.value.trim().length>=10&&[...document.querySelectorAll('[data-cv-check]')].every(x=>x.checked));}
document.addEventListener('change',e=>{if(!ctx||!e.target.closest('#conversation'))return;if(e.target.id==='cv-rate')ctx.rate=Number(e.target.value);if(e.target.id==='cv-mode'){ctx.typed=get('cv-own-words')?.value||ctx.typed;ctx.mode=e.target.value;stopSpeech();stopRecording();paint();}if(e.target.matches('[data-cv-check]'))finishReady();});
document.addEventListener('input',e=>{if(!ctx||!e.target.closest('#conversation'))return;if(e.target.id==='cv-draft'){save({draft:e.target.value});finishReady();}if(e.target.id==='cv-reflection')save({reflection:e.target.value});if(e.target.id==='cv-own-words')ctx.typed=e.target.value;if(e.target.hasAttribute('data-cv-recall'))ctx.recallValues[Number(e.target.dataset.cvRecall)]=e.target.value;});
document.addEventListener('click',async eventClick=>{
 const b=eventClick.target.closest('[data-cv]');if(!b||!ctx||!b.closest('#conversation'))return;const a=b.dataset.cv,n=Number(b.dataset.idx),e=ctx.episode;
 switch(a){
 case'line':{const i=Number(b.dataset.lineId),l=e.lines[i];await speak(l.en,l.speaker,i);break;}
 case'play-all':await playAll();break;
 case'stop-audio':stopSpeech();status('Audio detenido.');break;
 case'next-line':stopSpeech();ctx.visible=Math.min(8,ctx.visible+2);paint();break;
 case'show-all':stopSpeech();ctx.visible=8;paint();break;
 case'complete':complete();break;
 case'phrase':ctx.seen.add(n);paint();break;
 case'phrase-audio':await speak(e.chunks[n].example);break;
 case'answer':{if(ctx.feedback==='correct')break;const correct=n===ctx.turn*2+1;ctx.selected=n;ctx.feedback=correct?'correct':'retry';save({attempts:rec().attempts+1,correct:rec().correct+(correct?1:0)});paint();break;}
 case'next-turn':stopSpeech();ctx.turn++;ctx.selected=null;ctx.feedback='';paint();break;
 case'toggle-model':ctx.model=!ctx.model;ctx.typed=get('cv-own-words')?.value||ctx.typed;paint();break;
 case'model-audio':await speak(e.lines[ctx.voiceTurn*2+1].en,1);break;
 case'record':await record();break;
 case'recognise':recognise();break;
 case'compare':{const input=get('cv-own-words').value.trim();if(!input){status('Escribe o dicta una respuesta antes de comparar.');break;}const model=e.lines[ctx.voiceTurn*2+1].en;get('cv-comparison').innerHTML=`<div class="cv-notice"><b>${transcriptMatch(input,model)}% de coincidencia de palabras con el guion</b><p>Modelo: <span lang="en">${esc(model)}</span></p><p>Una respuesta distinta puede ser correcta. Esta comparación no evalúa pronunciación, significado ni gramática.</p></div>`;break;}
 case'voice-next':stopSpeech();stopRecording();recognition?.abort();recognition=null;revokeAudio();ctx.voiceTurn++;ctx.typed='';ctx.model=false;paint();break;
 case'branch':ctx.choice=n;save({choice:n});paint();break;
 case'branch-audio':if(ctx.choice>=0)await speak(e.branches[ctx.choice].reply);break;
 case'finish':finishReady();if(!b.disabled){save({draft:get('cv-draft').value,reflection:get('cv-reflection').value});complete();}break;
 case'recall-show':ctx.recallOpen=true;paint();break;
 case'recall-good':case'recall-hard':if(!ctx.recallOpen)break;save(reviewConversation(rec(),a==='recall-good'));event();location.hash='journey';break;
 }
});
