import content from './deep-course.json';
import {reviewSchedule} from './study-memory.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=q=>document.querySelector(q);
const names=['Comprender','Construir','Leer','Escuchar','Expresarte','Recordar'];
const slugs=['learn','build','read','listen','create','recall'];
const day=()=>new Date().toLocaleDateString('en-CA');
let store,course,unit,pack,tab,quiz=null,playToken=0;
export const normaliseStudy=s=>String(s||'').toLowerCase().replace(/[’‘]/g,"'").replace(/\bi'm\b/g,'i am').replace(/\b(you|we|they)'re\b/g,'$1 are').replace(/\b(he|she|it)'s\b/g,'$1 is').replace(/\bdon't\b/g,'do not').replace(/\bdoesn't\b/g,'does not').replace(/\bdidn't\b/g,'did not').replace(/\bcan't\b/g,'cannot').replace(/\bwon't\b/g,'will not').replace(/\b(is|are|was|were|have|has|had|would|could|should|must)n't\b/g,'$1 not').replace(/\b(i|you|we|they)'ve\b/g,'$1 have').replace(/\b(i|you|he|she|it|we|they)'ll\b/g,'$1 will').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const shuffle=xs=>{const a=[...xs];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const speakButton=(text,label='Escuchar',rate=.85)=>`<button class="btn soft" data-study-say="${esc(text)}" data-rate="${rate}">▶ ${label}</button>`;
const key=suffix=>`u${unit.id}_${suffix}`;
const result=suffix=>store.getState().study[key(suffix)];
const draft=id=>store.getState().studyDrafts[key(id)]||'';
const textarea=(id,label,rows=5)=>`<label class="study-label" for="study-${id}">${label}</label><textarea id="study-${id}" data-study-draft="${id}" lang="en" rows="${rows}" maxlength="2400">${esc(draft(id))}</textarea><small class="study-save" data-study-save>Tu texto se guarda en el progreso de este nivel.</small>`;
function saveResult(suffix,score,self=false,extra={}){const p=store.getState(),k=key(suffix),old=p.study[k]||{};p.study[k]={score,best:Math.max(old.best||0,score),attempts:(old.attempts||0)+1,date:day(),updated:Date.now(),due:old.due||0,reviews:old.reviews||0,self,...extra};p.activity[day()]=(p.activity[day()]||0)+1;store.save(p);}
function stageComplete(i){if(i===1)return[0,1,2,3].every(n=>(result('p'+n)?.best||0)>=80);if(i===5)return(result('recall')?.reviews||0)>=3;return!!result('s'+i);}
export function studySummary(s){const p=s.getState();return{started:new Set(Object.keys(p.study).map(k=>k.split('_')[0])).size,practices:Object.keys(p.study).filter(k=>/_p/.test(k)&&p.study[k].best>=80).length,due:Object.entries(p.study).filter(([k,v])=>k.endsWith('_recall')&&v.due&&v.due<=Date.now()).length};}
export function studyLink(u){return `<a class="study-unit-link" href="#study/${u.id}/learn"><span>CUADERNO DE PROFUNDIZACIÓN</span><b>Trabaja esta unidad en 6 etapas →</b><small>Más explicación, un caso nuevo, práctica escrita, escucha, proyecto y repasos.</small></a>`;}
export function buildStudyQuestions(u,p){
 const meaning=u.questions.map((q,i)=>({...q,id:'m'+i,type:'choice'}));
 meaning.push({id:'contrast',type:'choice',prompt:'Elige el modelo recomendado para la intención explicada en esta unidad.',options:[p.contrast[0],p.contrast[1].replace(/\s*\[.*?\]/g,'')],answer:p.contrast[0],why:p.contrast[2]});
 const build=u.rules.flatMap((r,j)=>r.examples.map((sentence,i)=>({id:`b${j}${i}`,type:'order',prompt:'Reconstruye el ejemplo. Después explica qué comunica.',answer:sentence,why:r.text,rule:r.title})));
 const recall=u.vocab.slice(0,6).map((v,i)=>({id:'v'+i,type:'typed',prompt:`Recuerda la expresión de esta unidad: ${v.es}.`,hint:`Primera letra: ${v.en[0]}. ${v.en.trim().split(/\s+/).length} palabra(s).`,answer:v.en,why:`${v.en} — ${v.es}. Úsala ahora en una frase propia.`}));
 const lines=p.text.match(/[^.!?]+[.!?]+/g)||[p.text];
 const listen=lines.filter(x=>x.trim().split(/\s+/).length<=23).slice(0,6).map((x,i)=>({id:'d'+i,type:'dictation',prompt:'Escucha y escribe. Puedes repetir el audio; cuenta tu primera respuesta.',answer:x.trim(),why:'Compara las palabras y el orden con el modelo. La puntuación y las mayúsculas no afectan a esta comprobación.'}));
 return[meaning,build,recall,listen];
}
function overview(){const p=store.getState(),sum=studySummary(store);return `<div id="study-root"><section class="study-hero"><div><p class="eyebrow">APRENDER ES VOLVER A USARLO</p><h2>Menos prisa.<br>Más profundidad.</h2><p>24 talleres de ${store.courseId.toUpperCase()}. Reparte cada unidad en sesiones: comprende, recupera de memoria y aplica lo aprendido a un caso diferente.</p></div><div class="study-hero-stat"><b>${sum.due}</b><span>repasos pendientes</span><small>${sum.started} talleres iniciados · ${sum.practices}/96 rondas con 80% o más</small></div></section><section class="panel"><h3>Una semana posible, a tu ritmo</h3><div class="study-week">${['Día 1 · Comprende + construye','Día 2 · Recupera + lee','Día 3 · Escucha + conversa','Día 4 · Escribe + revisa','Día 7 · Recuerda sin mirar','Después · Retoma lo difícil'].map(x=>`<span>${x}</span>`).join('')}</div><p>Prueba sesiones de 20–35 minutos y ajústalas a tu atención. Puedes abrir cualquier etapa. Los repasos espaciados registran la recuperación en días posteriores; repetir todo hoy no adelanta esas fechas.</p><p class="tiny">Duración orientativa, sin bloqueo de contenido. Completar tareas no equivale a certificar un nivel. La expresión libre utiliza modelos y autoevaluación.</p></section><div class="study-catalog">${course.units.map(u=>{const r=p.study[`u${u.id}_recall`];return `<a class="panel study-card" href="#study/${u.id}/learn"><span class="eyebrow">UNIDAD ${String(u.id).padStart(2,'0')}</span><h3>${u.icon} ${esc(u.title)}</h3><p>${esc(u.goal)}</p><div class="study-card-foot"><span>6 etapas · 4 rondas de práctica</span><b>${r?.due&&r.due<=Date.now()?'Repaso pendiente ↗':r?.reviews?'Repasos: '+r.reviews:'Entrar →'}</b></div></a>`;}).join('')}</div></div>`;}
export function renderStudy(s,c,id,section='learn'){store=s;course=c;quiz=null;unit=c.units[Number(id)-1];if(!unit)return overview();pack=content[s.courseId][unit.id-1];tab=slugs.includes(section)?section:'learn';return frame();}
function frame(){return `<div id="study-root"><a class="back-link" href="#study">← Todos los talleres</a><section class="study-heading"><div><p class="eyebrow">${store.courseId.toUpperCase()} · UNIDAD ${String(unit.id).padStart(2,'0')}</p><h2>${esc(unit.title)}</h2><p>${esc(unit.goal)}</p></div><a class="btn ghost" href="#unit/${unit.id}">Lecciones y vocabulario</a></section><nav class="study-stages" aria-label="Etapas del taller">${names.map((x,i)=>`<a href="#study/${unit.id}/${slugs[i]}" ${tab===slugs[i]?'aria-current="step"':''}><span>${stageComplete(i)?'✓':i+1}</span>${x}</a>`).join('')}</nav><div id="study-stage">${({learn:learn,build:build,read:read,listen:listen,create:create,recall:recall}[tab])()}</div><p class="tiny study-note">Las tareas de comprensión y producción incluyen autoevaluación. Las rondas estructuradas comprueban respuestas concretas; no califican automáticamente la calidad de un texto libre.</p></div>`;}
function repaint(){const el=$('#study-root');if(el)el.outerHTML=frame();}
function markButton(i,label='Registrar mi práctica'){return `<button class="btn primary" data-study-mark="${i}">${result('s'+i)?'Práctica registrada · actualizar':label}</button><span id="study-message" role="status"></span>`;}
function learn(){return `<section class="panel study-start"><span class="pill blue">ANTES DE VER SOLUCIONES</span><h3>¿Qué puedes hacer ya?</h3><p>Intenta decir dos frases sobre este tema. Identifica qué te falta para lograr este objetivo: ${esc(unit.goal)}</p><p>Trabaja una explicación cada vez. Mira el modelo, tapa la explicación, cambia un dato y comprueba si puedes explicar por qué funciona.</p></section>${pack.insights.map((r,i)=>`<section class="panel study-explanation"><span class="study-number">0${i+1}</span><h3>${esc(r.title)}</h3><p>${esc(unit.rules[i].text)}</p><p>${esc(r.text)}</p><div class="pattern">${esc(unit.rules[i].pattern)}</div><div class="study-examples">${unit.rules[i].examples.map(x=>`<div><p lang="en">${esc(x)}</p>${speakButton(x,'Oír ejemplo')}</div>`).join('')}</div><p class="study-callout"><b>Vigila este detalle:</b> ${esc(unit.rules[i].tip)}</p><details><summary>Practica sin copiar</summary><ol><li>Explica el significado del primer ejemplo con palabras sencillas.</li><li>Cambia una persona, un objeto o un momento y conserva la intención.</li><li>Di la versión nueva sin mirar y después revisa su forma.</li></ol></details></section>`).join('')}<section class="panel"><h3>Un contraste que importa</h3><div class="study-contrast"><div><span>Modelo para esta intención</span><p lang="en">${esc(pack.contrast[0])}</p></div><div><span>Forma que revisar</span><p>${esc(pack.contrast[1])}</p></div></div><p>${esc(pack.contrast[2])}</p>${textarea('notes','Tu explicación: escribe un ejemplo propio y la diferencia que necesitas recordar.',4)}<div class="button-row">${markButton(0,'Ya lo expliqué con un ejemplo propio')}<a class="btn soft" href="#study/${unit.id}/build">Ir a la práctica →</a></div></section>`;}
function build(){const banks=buildStudyQuestions(unit,pack);return `<section class="panel"><p class="eyebrow">RECONOCER · CONSTRUIR · RECUPERAR</p><h3>Practica en cuatro direcciones</h3><p>Cada ronda tiene un propósito distinto. Intenta responder antes de mirar la ayuda. La nota utiliza el primer intento de cada pregunta: corregir enseña, y una ronda posterior muestra si ya puedes recordarlo.</p><div class="study-rounds">${['Decide el significado','Reconstruye la frase','Recuerda el vocabulario','Dictado del caso nuevo'].map((t,i)=>{const r=result('p'+i);return `<article><span class="study-number">${i+1}</span><h4>${t}</h4><p>${banks[i].length} ejercicios · ${r?'mejor resultado: '+r.best+'%':'sin completar'}</p><button class="btn primary" data-study-quiz="${i}">${r?'Practicar otra vez':'Empezar ronda'}</button></article>`;}).join('')}</div></section><div id="study-quiz"></div>`;}
function factPrompts(){return `<ol class="study-questions">${pack.facts.map(([q,a],i)=>`<li><p lang="en">${esc(q)}</p><details><summary>Comparar con la respuesta de referencia</summary><p lang="en">${esc(a)}</p><p class="tiny">Puedes responder con otras palabras si conservas el significado. Busca la evidencia en el texto.</p></details></li>`).join('')}</ol>`;}
function read(){return `<section class="panel"><p class="eyebrow">UN CASO NUEVO · ${pack.text.split(/\s+/).length} PALABRAS</p><h3>${esc(pack.readTitle)}</h3><p>Primera lectura: explica de qué trata en una frase. Segunda: localiza la evidencia para las preguntas. Tercera: oculta el texto y reconstruye lo esencial con palabras propias.</p><div class="button-row">${speakButton(pack.text,'Oír el caso')}<button class="btn ghost" data-study-toggle="study-passage">Mostrar / ocultar lectura</button></div><div class="study-passage" id="study-passage" lang="en">${esc(pack.text)}</div><details class="reading-support"><summary>Apoyo de vocabulario · sentido en este tema</summary><div class="study-glossary">${pack.glossary.map(v=>`<article><b lang="en">${esc(v.en)}</b><span>${esc(v.es)}</span>${speakButton(v.en,'Oír')}</article>`).join('')}</div><p class="tiny">Estas expresiones también aparecen en el vocabulario de la unidad, donde puedes guardarlas en tarjetas.</p></details>${factPrompts()}${textarea('reading','Escribe la idea principal, tres respuestas y una frase propia que conecte el caso con el tema.',6)}<details><summary>Comprueba la calidad de tu respuesta</summary><ul><li>¿Las respuestas se apoyan en el texto?</li><li>¿Distingo lo que dice de lo que yo supongo?</li><li>¿Puedo contarlo sin copiar frases enteras?</li><li>¿He usado una estructura de la unidad en un ejemplo nuevo?</li></ul></details><div class="button-row">${markButton(2,'He comparado mis respuestas con el texto')}</div></section>`;}
function listen(){const text=unit.listening?.text||unit.dialogue.map(([a,t])=>`${a}. ${t}`).join(' ');const prompts=unit.listening?.questions.map(q=>[q.prompt,q.answer])||unit.dialogue.filter((_,i)=>i%2===0).map(([a,t])=>[`${a}: ${t}`,'Contesta con tus propios datos y compara con el diálogo.']);return `<section class="panel"><p class="eyebrow">PRIMERO EL MENSAJE; DESPUÉS LOS DETALLES</p><h3>Escucha sin leer la transcripción</h3><p>1. Escucha una vez y anota quién habla y para qué. 2. Lee las preguntas y escucha de nuevo. 3. Comprueba solo la parte que no entendiste. 4. Vuelve a velocidad normal.</p><div class="button-row">${speakButton(text,'Velocidad normal',1)}${speakButton(text,'Más lento',.65)}<button class="btn ghost" data-study-stop>Detener</button></div><ol>${prompts.map(([q,a])=>`<li><p>${esc(q)}</p><details><summary>Ver referencia</summary>${esc(a)}</details></li>`).join('')}</ol><details><summary>Consultar transcripción después de intentarlo</summary><p class="study-passage" lang="en">${esc(text)}</p></details>${textarea('listening','Antes y después: anota lo que entendiste primero, dos detalles y qué cambió al repetir.',5)}<div class="button-row">${markButton(3,'He escuchado, comprobado y vuelto a escuchar')}</div></section><section class="panel"><h3>Del oído a tu propia voz</h3><p>Escucha una intervención, repítela en la pausa y luego cambia un dato. Mantén la intención y la sílaba destacada. La velocidad lenta es un apoyo, no una meta permanente.</p><div class="study-dialogue">${unit.dialogue.map(([a,t],i)=>`<article><span>${esc(a)}</span><p lang="en">${esc(t)}</p>${speakButton(t,'Oír y repetir')}<a href="#lab" class="text-link" data-study-mouth="${esc(t)}">Ver sonidos de esta frase →</a></article>`).join('')}</div><p class="tiny">Audio sintetizado por las voces del dispositivo. Escuchar otras voces y conversaciones reales ayuda a transferir la práctica.</p></section>`;}
function create(){const min={a1:20,a2:55,b1:90}[store.courseId];return `<section class="panel"><p class="eyebrow">TU TURNO · SIN COPIAR EL MODELO</p><h3>Conversaciones con un propósito</h3><div class="study-missions">${pack.transfer.map((t,i)=>`<article><span class="study-number">${i+1}</span><h4>${esc(t)}</h4><p>Interpreta los dos papeles o practícalo con alguien. Primera vuelta con notas; segunda cambiando un dato; tercera con una pregunta inesperada.</p></article>`).join('')}</div><details><summary>Preguntas para mantener el intercambio</summary><p lang="en">Could you explain that? · What do you mean? · What about you? · Why do you think that? · So, do you mean…?</p><p>Elige las que puedas usar con naturalidad. Puedes pedir repetición o reformular con palabras más sencillas.</p></details></section><section class="panel"><h3>Tu proyecto de la unidad</h3><p class="study-project">${esc(pack.challenge)}</p><p>Planifica → escribe → revisa el significado → revisa la forma → dilo sin leer. Si necesitas apoyo, consulta las explicaciones y vuelve a tu propio caso.</p>${textarea('project','Tu primer borrador y tu versión revisada',9)}<div class="study-rubric"><h4>Autoevaluación de tu producción</h4>${['He cubierto todos los puntos pedidos.','He incluido detalles propios y comprensibles.','He revisado la estructura central de esta unidad.','He leído o dicho mi versión y detectado una mejora.'].map((t,i)=>`<label><input type="checkbox" data-study-rubric="${i}"> ${t}</label>`).join('')}</div><p class="tiny">Para registrar esta etapa, escribe al menos ${min} palabras y usa la lista. Es una comprobación de práctica realizada, no una nota automática de gramática. La extensión recomendada del proyecto, si se indica, es una meta adicional.</p><div class="button-row">${markButton(4,'He revisado mi proyecto')}${speakButton(draft('project'),'Escuchar mi borrador')}</div></section>`;}
function recall(){const r=result('recall'),date=r?.due?new Date(r.due).toLocaleDateString('es',{day:'numeric',month:'long'}):null;return `<section class="panel"><p class="eyebrow">RECUPERACIÓN ESPACIADA</p><h3>¿Puedes recordarlo después?</h3><p>La familiaridad al releer puede engañar. Prueba una ronda sin abrir las explicaciones y usa los errores para decidir qué volver a estudiar.</p><div class="study-review-line">${['Punto de partida','+1 día','+3 días','+7 días','+14 días','+30 días'].map((t,i)=>`<span class="${r&&(i===0||i<=r.reviews)?'review-done':''}">${r&&(i===0||i<=r.reviews)?'✓ ':''}${t}</span>`).join('')}</div><p>${date?`Próximo repaso registrado: <b>${date}</b>. Has realizado ${r.reviews} repaso(s) espaciado(s) con 80% o más.`:'La primera ronda establece tu punto de partida y programa el siguiente repaso.'}</p><p>Los intervalos se cuentan desde cada repaso válido. Puedes practicar antes; las repeticiones anticipadas no adelantan el calendario. Tres repasos posteriores marcan esta etapa como practicada, y la ruta continúa con intervalos más largos.</p><button class="btn primary" data-study-quiz="review">${r?.due>Date.now()?'Practicar ahora sin adelantar la fecha':'Empezar recuperación'}</button><div id="study-quiz"></div></section><section class="panel"><h3>Comprueba la transferencia</h3><p>Sin mirar el proyecto anterior: ${esc(pack.transfer[unit.id%3])}</p>${textarea('reflection','Qué recuerdo, qué todavía confundo y qué practicaré en la próxima sesión.',4)}<a class="btn soft" href="#study">Elegir otro taller</a></section>`;}
function startQuiz(mode){const banks=buildStudyQuestions(unit,pack);let questions;if(mode==='review'){questions=shuffle([...banks[0],...banks[1],...banks[2]]).slice(0,10);if(unit.id>1){const prev=course.units[unit.id-2],pp=content[store.courseId][unit.id-2];questions=questions.slice(0,8).concat(shuffle(buildStudyQuestions(prev,pp).flat().filter(q=>q.type!=='dictation')).slice(0,2).map(q=>({...q,id:'prev'+q.id,prompt:`Repaso de la unidad ${prev.id}: ${q.prompt}`})));}}else questions=shuffle(banks[Number(mode)]);quiz={mode,questions,index:0,correct:0,wrong:[],answered:false,selected:[],tokens:[],feedback:null};drawQuiz();$('#study-quiz')?.scrollIntoView({behavior:'smooth',block:'start'});}
function drawQuiz(){if(!quiz||!$('#study-quiz'))return;const q=quiz.questions[quiz.index];if(!q)return finishQuiz();quiz.tokens=q.type==='order'?shuffle(q.answer.replace(/[.!?]$/,'').split(/\s+/).map((t,i)=>({t,i}))):[];quiz.selected=[];$('#study-quiz').innerHTML=`<section class="study-exercise"><div class="section-heading"><span class="pill blue">${quiz.index+1} / ${quiz.questions.length}</span><button class="btn ghost" data-study-exit>Salir de la ronda</button></div><h3>${esc(q.prompt)}</h3>${q.rule?`<p class="tiny">${esc(q.rule)}</p>`:''}${q.type==='choice'?`<div class="study-options">${shuffle(q.options).map(o=>`<button data-study-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div>`:q.type==='order'?`<div id="study-ordered" class="study-ordered" aria-live="polite"></div><div id="study-tokens" class="study-tokens">${quiz.tokens.map(t=>`<button data-study-token="${t.i}">${esc(t.t)}</button>`).join('')}</div><button class="btn ghost" data-study-undo>Deshacer</button><button class="btn primary" data-study-check>Comprobar</button>`:`${q.type==='dictation'?speakButton(q.answer,'Escuchar dictado',.82):''}<label class="study-label" for="study-answer">Tu respuesta</label><input id="study-answer" autocomplete="off" spellcheck="false" lang="en"><div class="button-row"><button class="btn primary" data-study-check>Comprobar</button>${q.hint?`<button class="btn ghost" data-study-hint>Necesito una pista</button>`:''}</div><p id="study-hint"></p>`}<div id="study-feedback" role="status"></div></section>`;}
function answer(value){if(!quiz||quiz.answered)return;const q=quiz.questions[quiz.index],ok=normaliseStudy(value)===normaliseStudy(q.answer);quiz.answered=true;if(ok&&!quiz.hinted)quiz.correct++;else quiz.wrong.push(q.id);$('#study-feedback').innerHTML=`<div class="study-feedback ${ok?'is-right':'needs-work'}"><h4>${ok?quiz.hinted?'Lo resolviste con ayuda':'Respuesta correcta':'Compara y vuelve a construirlo'}</h4><p lang="en"><b>${esc(q.answer)}</b></p><p>${esc(q.why)}</p>${!ok?'<p>Di la versión corregida y explica el cambio antes de continuar.</p>':''}${quiz.hinted?'<p class="tiny">Esta respuesta usó una pista. Se registra como práctica con ayuda en esta ronda.</p>':''}</div><button class="btn primary" data-study-next>${quiz.index+1===quiz.questions.length?'Ver resultado':'Siguiente ejercicio →'}</button>`;}
function finishQuiz(){const score=Math.round(quiz.correct/quiz.questions.length*100),isReview=quiz.mode==='review',r=isReview?reviewSchedule(result('recall'),score):{};saveResult(isReview?'recall':'p'+quiz.mode,score,false,{wrong:quiz.wrong,...(isReview?{reviews:r.reviews,due:r.due}:{})});$('#study-quiz').innerHTML=`<section class="study-exercise"><p class="eyebrow">PRIMER INTENTO · SIN PISTAS</p><h3 class="study-score">${score}%</h3><p>${quiz.correct} de ${quiz.questions.length} respuestas correctas sin ayuda.</p><p>${score>=80?'Buen punto de apoyo. Comprueba ahora si puedes usarlo en una frase nueva.':'Vuelve a las explicaciones de lo que falló. Después inicia otra ronda, sin copiar las respuestas.'}</p>${isReview?`<p>${r.qualified?'Se programó el siguiente repaso.':'La fecha de repaso sigue pendiente; practicar antes o con menos del 80% no adelanta el intervalo.'}</p>`:''}<p>${quiz.wrong.length} respuestas para revisar, incluidas las realizadas con pistas.</p><div class="button-row"><button class="btn primary" data-study-quiz="${quiz.mode}">Otra ronda</button><a class="btn soft" href="#study/${unit.id}/learn">Revisar explicaciones</a><a class="btn ghost" href="#study/${unit.id}/create">Aplicarlo a mi caso</a></div></section>`;quiz=null;}
function say(text,rate=.85){if(!text.trim())return;if(!window.speechSynthesis){if($('#study-message'))$('#study-message').textContent='No hay lectura en voz alta en este navegador.';return;}playToken++;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=store.getState().accent||'en-US';u.rate=rate;u.voice=window.speechSynthesis.getVoices().find(v=>v.lang===u.lang)||null;window.speechSynthesis.speak(u);}
export function stopStudy(){playToken++;window.speechSynthesis?.cancel();quiz=null;}
document.addEventListener('input',e=>{const field=e.target.closest('[data-study-draft]');if(!field||!$('#study-root'))return;const p=store.getState();p.studyDrafts[key(field.dataset.studyDraft)]=field.value;store.save(p);const msg=field.nextElementSibling;if(msg)msg.textContent=store.localAvailable?'Borrador guardado en este dispositivo; se sincroniza si tu cuenta está conectada.':'El guardado local no está disponible. Copia tu texto antes de salir.';});
document.addEventListener('keydown',e=>{if(e.target.id==='study-answer'&&e.key==='Enter'){e.preventDefault();if(!quiz?.answered)answer(e.target.value);}});
document.addEventListener('click',e=>{if(!$('#study-root'))return;const b=e.target.closest('button,a');if(!b)return;
 if(b.hasAttribute('data-study-say')){const text=b.textContent.includes('mi borrador')?$('#study-project')?.value||'':b.dataset.studySay;say(text,Number(b.dataset.rate)||.85);}
 if(b.hasAttribute('data-study-stop'))window.speechSynthesis?.cancel();
 if(b.dataset.studyToggle){const target=$('#'+b.dataset.studyToggle);if(target)target.hidden=!target.hidden;}
 if(b.dataset.studyMouth){try{sessionStorage.setItem('hello-mouth-phrase',b.dataset.studyMouth);}catch{}}
 if(b.hasAttribute('data-study-mark')){const i=Number(b.dataset.studyMark),field={0:'notes',2:'reading',3:'listening',4:'project'}[i],min=i===4?{a1:20,a2:55,b1:90}[store.courseId]:8;const count=draft(field).trim().split(/\s+/).filter(Boolean).length;if(count<min){$('#study-message').textContent=`Escribe al menos ${min} palabras para dejar evidencia de tu práctica.`;return;}if(i===4&&document.querySelectorAll('[data-study-rubric]:checked').length<4){$('#study-message').textContent='Revisa los cuatro puntos de tu autoevaluación antes de registrarla.';return;}saveResult('s'+i,0,true);$('#study-message').textContent='Práctica registrada. Puedes volver para mejorar tu versión.';b.textContent='Práctica registrada · actualizar';}
 if(b.hasAttribute('data-study-quiz')){startQuiz(b.dataset.studyQuiz);return;}
 if(b.hasAttribute('data-study-exit')){quiz=null;repaint();return;}
 if(!quiz)return;
 if(b.hasAttribute('data-study-token')&&!quiz.answered){const n=Number(b.dataset.studyToken);if(!quiz.selected.includes(n)){quiz.selected.push(n);b.disabled=true;$('#study-ordered').textContent=quiz.selected.map(i=>quiz.tokens.find(t=>t.i===i).t).join(' ');}}
 if(b.hasAttribute('data-study-undo')&&!quiz.answered){const n=quiz.selected.pop();const token=$(`[data-study-token="${n}"]`);if(token)token.disabled=false;$('#study-ordered').textContent=quiz.selected.map(i=>quiz.tokens.find(t=>t.i===i).t).join(' ');}
 if(b.hasAttribute('data-study-answer'))answer(b.dataset.studyAnswer);
 if(b.hasAttribute('data-study-check')){const value=quiz.questions[quiz.index].type==='order'?$('#study-ordered').textContent:$('#study-answer').value;answer(value);}
 if(b.hasAttribute('data-study-hint')&&!quiz.answered){quiz.hinted=true;$('#study-hint').textContent=quiz.questions[quiz.index].hint;}
 if(b.hasAttribute('data-study-next')&&quiz.answered){quiz.index++;quiz.answered=false;quiz.hinted=false;drawQuiz();}
});
window.HelloStudy={buildStudyQuestions,reviewSchedule,normaliseStudy,content,studySummary};
